export declare namespace net_rpc_proto_applicationerrorcode {
    enum ApplicationEC {
        UNKNOWN_APPLICATION_ERROR = "UNKNOWN_APPLICATION_ERROR",
        OK = "OK",
        LOCK_RESOURCES_EXCEPTION = "LOCK_RESOURCES_EXCEPTION",
        INVALID_LOAD_ID = "INVALID_LOAD_ID",
        ILLEGAL_STATE = "ILLEGAL_STATE",
        AUTHENTICATION_FAILURE = "AUTHENTICATION_FAILURE",
        INVALID_SESSION_TOKEN = "INVALID_SESSION_TOKEN",
        SHORT_LIVED_SESSION = "SHORT_LIVED_SESSION",
        UNAUTHORIZED = "UNAUTHORIZED",
        INVALID_REQUEST = "INVALID_REQUEST",
        INVALID_RESPONSE = "INVALID_RESPONSE",
        ILLEGAL_VERSION = "ILLEGAL_VERSION",
        SERVER_ERROR = "SERVER_ERROR",
        HEALTH_FAILURE = "HEALTH_FAILURE",
        UNREACHABLE_ENDPOINT = "UNREACHABLE_ENDPOINT",
        INVALID_CONFIG = "INVALID_CONFIG",
        PERSISTER_FAILURE = "PERSISTER_FAILURE",
        MONGO_SOCKET_FAILURE = "MONGO_SOCKET_FAILURE",
        INTERRUPTED = "INTERRUPTED",
        CREATE_MERCHANT_FAILED = "CREATE_MERCHANT_FAILED",
        CREATE_STORE_FAILED = "CREATE_STORE_FAILED",
        ACCOUNT_ALREADY_EXISTS = "ACCOUNT_ALREADY_EXISTS"
    }
}
